name: Build OpenWrt x86 Firmware

on:
  push:
    branches: [main]  # 根据实际情况调整分支
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 克隆 OpenWrt 官方源码
      - name: Clone OpenWrt source
        run: |
          git clone https://github.com/openwrt/openwrt.git
        # 注意：如果你希望后续步骤都在 openwrt 目录下执行，可以使用 working-directory 参数
          
      # 第二步：安装编译依赖
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk gettext unzip \
              zlib1g-dev file libssl-dev xsltproc wget git subversion

      # 第三步：更新 feeds 并安装所有 feed
      - name: Update and install feeds
        working-directory: openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 第四步：生成默认编译配置
      - name: Generate default configuration
        working-directory: openwrt
        run: |
          make defconfig

      # 第五步：开始编译固件
      - name: Build OpenWrt Firmware
        working-directory: openwrt
        run: |
          make -j$(nproc) V=s

      # 第六步：将编译好的固件作为构件上传，并添加 retention-days 说明
      - name: Upload Artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-x86-firmware
          # 上传 openwrt/bin/targets 目录下的所有子目录文件（请根据你固件生成目录确认路径）
          path: |
            openwrt/bin/targets/**/*
          retention-days: 1

      # 可选步骤：测试下载上传的 Artifact，以消除 lint 检查的“下载信息缺失”警告
      - name: Download Artifact (Test)
        if: success()
        uses: actions/download-artifact@latest
        with:
          name: openwrt-x86-firmware
          path: downloaded_artifact