name: Build OpenWrt x86

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ccache ecj fastjar file g++ gawk \
        gettext git java-propose-classpath libelf-dev libncurses5-dev \
        libncursesw5-dev libssl-dev python3 python3-distutils python3-setuptools \
        rsync unzip wget zlib1g-dev

    - name: Clone OpenWrt Source
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        git checkout v23.05.3  # 使用稳定版本标签

    - name: Update Feeds
      run: |
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Apply Custom Config (可选)
      run: |
        cd openwrt
        cp ../config.seed .config  # 从仓库根目录复制预置配置
        make defconfig

    - name: Compile OpenWrt
      run: |
        cd openwrt
        make -j$(nproc) download
        make -j$(nproc) V=s

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4  # 升级到最新版本
      with:
        name: openwrt-bin
        path: openwrt/bin/targets/x86/64/*
        if-no-files-found: error  # 严格检查文件存在性